version: "3.9"

services:
  sanixdk.xyz:
    image: sanixdk.xyz:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - public/:/usr/share/nginx/html/
    ports:
      - "3003:8080"

volumes:
  public:
