name: Website build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actionV3
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install gcc make

      - name: Compile builder
        run: make compile

      - name: Build the website
        run: make polish && make build
